name: dispatch

on:
  push:
    branches: [ master ]
  release:
  
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: dispatch trigger parent(s) repo bump
        run: |
          curl -X POST https://api.github.com/repos/billypchan/carthageDummyC/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.D_SECRET }} \
          -d '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
           
          curl -X POST https://api.github.com/repos/billypchan/carthageDummyD/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.D_SECRET }} \
          -d '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
           
          curl -X POST https://api.github.com/repos/billypchan/carthageDummyB/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.D_SECRET }} \
          -d '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
