name: Remote Dispatch Action Responder

on:
  repository_dispatch:
    types: [ping]
  push:
    branches: [ master ]

jobs:
  create-bump-pr:
    runs-on: macos-10.15

    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"

      - name: checkout
        uses: actions/checkout@v2

      - name: create bump PR
        run: |
          get_latest_release() {
            curl --silent "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
            grep '"tag_name":' |                                            # Get tag line
            sed -E 's/.*"([^"]+)".*/\1/'                                    # Pluck JSON value
          }
          
          LATEST_VERSION=get_latest_release "billypchan/carthageDummyE"

          git branch chore/bump
          git checkout chore/bump
          echo "before update"
          cat Cartfile
          sed -i '' 's/\(github "billypchan\/carthageDummyE" ~> \)\(.*\)$/\1$LATEST_VERSION/g' Cartfile
          echo "after update"
          cat Cartfile
          carthage update --no-build
          git add .
          git commit -m"bump E"
          git push --set-upstream origin chore/bump

      - name: open PR
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --title "chore: bump" --body "bump for E"
