name: Remote Dispatch Action Responder

on:
  repository_dispatch:
    types: [ping]
  push:
    branches: [ master ]

jobs:
  create-bump-pr:
    runs-on: macos-10.15

    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload.repository }}'"

      - name: checkout
        uses: actions/checkout@v2

      - name: create bump PR
        run: |
          sed -i '' 's/\(github "billypchan\/carthageDummyE" ~> \)\(.*\)$/\12.0/g' ./Cartfile
          cat Cartfile
          git branch chore/bump
          git checkout chore/bump
          git add .
          git commit -m"bump E"
          git log
          git push
